name: Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup-vsdevenv
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true
      
    - name: run-cmake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: Release
        
    - name: build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ env.BUILD_TYPE }}
        path: build/bin
